ripes: 2.2.6 -> 2.2.6-unstable-2024-01-02
Without the change the build fails on `master` as
https://hydra.nixos.org/build/247694706:

    In file included from /build/source/external/VSRTL/interface/vsrtl_vcdfile.cpp:1:
    /build/source/external/VSRTL/interface/vsrtl_vcdfile.h:31:20: error: 'uint64_t' has not been declared
       31 |     void writeTime(uint64_t time);
          |                    ^~~~~~~~

As the fix was done in one of the external modules it seemed easier to
pull unstable `master` version. Switched to `qt6` and checked if it
starts.